# Generated by Django 4.1.3 on 2022-11-06 14:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.IntegerField(blank=True, null=True, verbose_name='Blood group')),
                ('emergency_contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, null=True, region=None, unique=True, verbose_name='Emergency contact number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('marital_status', models.CharField(blank=True, max_length=100, verbose_name='Marital status')),
                ('registration_date', models.DateTimeField(auto_now=True, verbose_name='Registration date')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='users.user', verbose_name='User')),
            ],
        ),
    ]
