# Generated by Django 4.1.3 on 2022-11-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.AlterField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Registration date'),
        ),
    ]
