# Generated by Django 4.1.3 on 2022-11-05 20:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(blank=True, max_length=12, verbose_name='IIN')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('middle_name', models.CharField(blank=True, max_length=30, verbose_name='middle name')),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=12, region=None, unique=True)),
            ],
        ),
    ]
