# Generated by Django 4.1.3 on 2022-11-06 14:15

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.SmallIntegerField(verbose_name='Department ID')),
                ('specialization_details_id', models.SmallIntegerField(verbose_name='Specialization Details ID')),
                ('experience_in_years', models.SmallIntegerField(verbose_name='Experience in years')),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='doctor/photos/', verbose_name='Photo')),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Highest'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth')], default=4, verbose_name='Category')),
                ('price_per_appointment', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Price Per Appointment')),
                ('schedule_details', models.CharField(max_length=256, verbose_name='Schedule Details')),
                ('degree', models.PositiveSmallIntegerField(choices=[(0, 'Bachelors'), (1, 'Masters'), (3, 'PHD'), (4, 'Doctorate')], default=3, verbose_name='Degree')),
                ('rating', models.PositiveSmallIntegerField(default=0, verbose_name='Rating')),
                ('homepage_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='Homepage URL')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='users.user', verbose_name='User')),
            ],
        ),
    ]
